### ISSUE TITLE
Setting layout from storyboard

### ISSUE THREAD

**Issue by pigpox** [bernikowich/StickyHeaderFlowLayout#1]
good afternoon,
i currently have a tableview that is my rootcontroller, you tap on the cell and it pushes into the uicollectionview controller (where i want to use your library). But its not working correctly bc of 

`window.rootViewController = collectionViewController`

you know how i can change this ?

thanks

**Comment by bernikovich** [comment]
Hello.
Can you provide me with a sample project where I can reproduce the issue?

**Comment by pigpox** [comment]
yeah as soon as i get hm from work today...

**Comment by pigpox** [comment]
[testApps.zip](https://github.com/bernikowich/StickyHeaderFlowLayout/files/3025051/testApps.zip)

ok here you go...

**Comment by bernikovich** [comment]
@badfranco if I understand you correctly. You want to use `StickyHeaderFlowLayout` in storyboard. I changed following:
1. Change `CollectionViewFlowLayout` class to `StickyHeaderFlowLayout`;
2. Set cell identifier to `StickyHeaderParallexHeader` (it is `wall` right now).

**Comment by bernikovich** [comment]
You don't need to setup your view controller from app delegate, you can use your storyboard too.

**Comment by pigpox** [comment]
thank you!! after some experimentation (im a noob) this is how it done 
<img width="1402" alt="Screen Shot 2019-04-03 at 7 14 20 PM" src="https://user-images.githubusercontent.com/11565568/55521108-eddd9f00-5644-11e9-8382-6739b75277fd.png">
hightlight `StickyHeaderFlowLayout` and to the right add the class on the storyboard
